# Generated by Django 5.1.5 on 2025-02-07 21:51

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building_code', models.CharField(default='UNKNOWN', max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('civic_address', models.CharField(default='UNKNOWN', max_length=255)),
                ('campus', models.CharField(default='SGW', max_length=10)),
                ('parking_lot', models.BooleanField(default=False)),
                ('accessibility', models.BooleanField(default=False)),
                ('atm', models.BooleanField(default=False)),
                ('bikerack', models.BooleanField(default=False)),
                ('infokiosk', models.BooleanField(default=False)),
                ('services_links', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('departments_links', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('mode_of_travel', models.CharField(choices=[('walking', 'Walking'), ('driving', 'Driving')], max_length=10)),
            ],
        ),
    ]
