# Generated by Django 5.1.5 on 2025-01-31 21:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='accessibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='atm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='bikerack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='building_code',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.CharField(default='SGW', max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='civic_address',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='departments_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='building',
            name='infokiosk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='parking_lot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='services_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
    ]
