# Generated by Django 5.1.5 on 2025-01-31 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapengine', '0002_building_accessibility_building_atm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShuttleStop',
        ),
    ]
